language: python
install:
  - python setup.py install
  - pip install pdoc3
  - pdoc --html --output-dir docs skplumber
  - rm -r skplumber
script:
  - nosetests -s -v
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs/skplumber
  on:
    branch: master
